name: Validate Markdown Files

on:
  pull_request:
    paths:
      - 'src/content/initiatives/**.md'

jobs:
  validate-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Validate Markdown files
        run: npx astro check