name: Label Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/content/initiatives/**.md'

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: src/content/initiatives/**.md

      - name: Label PR
        id: label-pr
        run: |
          echo "Checking for new and edited files..."
          NEW_FILES=$(echo "${{ steps.changed-files.outputs.all_added_files }}" | tr ',' '\n' | grep 'src/content/initiatives/')
          EDITED_FILES=$(echo "${{ steps.changed-files.outputs.all_modified_files }}" | tr ',' '\n' | grep 'src/content/initiatives/')
          
          if [ -n "$NEW_FILES" ]; then
            echo "New files detected."
            echo "new" >> $GITHUB_ENV
          fi
          
          if [ -n "$EDITED_FILES" ]; then
            echo "Edited files detected."
            echo "edit" >> $GITHUB_ENV
          fi

      - name: Apply labels
        if: env.new == 'new' || env.edit == 'edit'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.new }},${{ env.edit }}