name: Update PR Information

on:
  pull_request:
    types: [closed]
    paths:
      - 'src/content/initiatives/**.md'

jobs:
  update-pr-info:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: src/content/initiatives/**.md
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Update PR information in changed initiative files
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Processing $file..."
            node scripts/add-pr-info.js "$file" ${{ github.event.pull_request.number }} "${{ github.event.pull_request.title }}" "${{ github.event.pull_request.user.login }}" "${{ github.event.pull_request.merged_at }}"
          done
      
      - name: Commit and push changes
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update PR info for PR #${{ github.event.pull_request.number }}"
          git push
